// Fixed current-schema backup projection. Unknown native fields are rejected by the database.
export const SOURCE_COLUMNS: Record<string, string[]> = {
  product_categories: "id organization_id name is_active created_at updated_at description".split(" "),
  suppliers: "id organization_id name company phone email address notes is_active created_at updated_at outstanding_balance".split(" "),
  customers: "id organization_id branch_id name phone email address notes credit_limit is_archived archived_at created_at updated_at outstanding_balance".split(" "),
  products: "id organization_id branch_id category_id supplier_id name sku barcode type purchase_price sale_price stock_quantity minimum_stock default_warranty service_type service_pricing_mode default_commission_amount default_commission_percent requires_account_number requires_provider requires_reference notes is_active created_at updated_at allow_sell_at_loss sell_at_loss_reason sell_at_loss_updated_at sell_at_loss_updated_by image_path".split(" "),
  invoices: "id organization_id branch_id customer_id invoice_no status subtotal discount_total customer_credit_applied grand_total amount_paid balance_due note created_by invoice_date created_at updated_at amount_tendered change_due checkout_idempotency_key".split(" "),
  credit_payments: "id organization_id branch_id customer_id amount method reference_number notes received_by created_at updated_at".split(" "),
  customer_write_offs: "id organization_id branch_id customer_id amount reason written_by created_at updated_at".split(" "),
  supplier_purchases: "id organization_id branch_id supplier_id purchase_no status purchase_date subtotal discount_total grand_total amount_paid balance_due reference_no notes created_by created_at updated_at".split(" "),
  supplier_write_offs: "id organization_id branch_id supplier_id amount reason written_by created_at updated_at".split(" "),
  product_stock_lots: "id organization_id branch_id product_id supplier_id lot_number purchase_date quantity_received quantity_remaining unit_cost notes is_active created_by created_at updated_at".split(" "),
  invoice_items: "id organization_id invoice_id product_id product_name product_type quantity purchase_price unit_price item_discount line_total service_provider service_direction service_account_number service_receiver_account service_reference_no service_transaction_amount service_commission service_total_charged service_note created_at updated_at allow_sell_at_loss_snapshot loss_override_reason_snapshot effective_unit_price_snapshot loss_amount_snapshot".split(" "),
  payments: "id organization_id branch_id invoice_id customer_id method amount reference_no note received_by paid_at created_at updated_at".split(" "),
  returns: "id organization_id branch_id invoice_id customer_id return_no status subtotal refund_amount refund_method reference_number notes created_by created_at updated_at".split(" "),
  supplier_payments: "id organization_id branch_id supplier_id purchase_id method amount reference_no note paid_at created_by created_at updated_at".split(" "),
  customer_ledger_entries: "id organization_id branch_id customer_id invoice_id payment_id credit_payment_id entry_type direction amount balance_after description reference_number created_by created_at updated_at".split(" "),
  supplier_ledger_entries: "id organization_id branch_id supplier_id purchase_id payment_id entry_type direction amount balance_after description reference_number created_by created_at updated_at".split(" "),
  invoice_item_stock_allocations: "id organization_id invoice_id invoice_item_id product_id stock_lot_id quantity unit_cost created_at".split(" "),
  stock_movements: "id organization_id branch_id product_id stock_lot_id movement_type quantity unit_cost reference_type reference_id invoice_id invoice_item_id notes created_by created_at".split(" "),
  supplier_purchase_items: "id organization_id purchase_id product_id product_name quantity unit_cost line_total stock_lot_id notes created_at".split(" "),
  return_items: "id organization_id return_id invoice_id invoice_item_id product_id item_name item_type quantity unit_price line_total restock created_at".split(" "),
  return_stock_allocations: "id organization_id return_id return_item_id product_id stock_lot_id quantity unit_cost created_at".split(" "),
  cash_shifts: "id organization_id branch_id opened_at closed_at opened_by closed_by starting_cash expected_cash counted_cash cash_difference notes status created_at updated_at".split(" "),
  expenses: "id organization_id branch_id category amount payment_method vendor_name notes status spent_at created_by archived_at archived_by created_at updated_at".split(" "),
  repairs: "id organization_id branch_id customer_id job_no customer_name customer_phone device_type device_model serial_imei problem_description diagnosis estimated_cost advance_paid final_cost status expected_delivery_at delivered_at notes created_by created_at updated_at accessories_received payment_method".split(" "),
  daily_closings: "id organization_id branch_id closing_date bills_count cash_sales digital_payments credit_pending expenses_total refunds_total service_commission_earned service_cash_in service_cash_out expected_closing_cash actual_closing_cash cash_difference notes finalized_by created_at updated_at finalized_at credit_collection_cash credit_collection_digital credit_write_offs".split(" "),
  staff_permissions: "id organization_id profile_id can_sell can_discount can_return can_void_invoice can_view_reports can_manage_stock can_sell_at_loss can_change_settings created_at updated_at".split(" "),
  loss_prevention_events: "id organization_id branch_id product_id invoice_id actor_id event_type reason cost_amount effective_sale_amount loss_amount metadata created_at".split(" "),
  audit_logs: "id organization_id branch_id actor_id module action details metadata created_at".split(" "),
};

export const SOURCE_REFERENCES: Record<string, Record<string, string>> = {
  product_categories: {"organization_id":"organizations"},
  suppliers: {"organization_id":"organizations"},
  customers: {"branch_id":"branches","organization_id":"organizations"},
  products: {"branch_id":"branches","category_id":"product_categories","organization_id":"organizations","sell_at_loss_updated_by":"profiles","supplier_id":"suppliers"},
  invoices: {"branch_id":"branches","created_by":"profiles","customer_id":"customers","organization_id":"organizations"},
  credit_payments: {"branch_id":"branches","customer_id":"customers","organization_id":"organizations","received_by":"profiles"},
  customer_write_offs: {"branch_id":"branches","customer_id":"customers","organization_id":"organizations","written_by":"profiles"},
  supplier_purchases: {"branch_id":"branches","created_by":"profiles","organization_id":"organizations","supplier_id":"suppliers"},
  supplier_write_offs: {"branch_id":"branches","organization_id":"organizations","supplier_id":"suppliers","written_by":"profiles"},
  product_stock_lots: {"branch_id":"branches","created_by":"profiles","organization_id":"organizations","product_id":"products","supplier_id":"suppliers"},
  invoice_items: {"invoice_id":"invoices","organization_id":"organizations","product_id":"products"},
  payments: {"branch_id":"branches","customer_id":"customers","invoice_id":"invoices","organization_id":"organizations","received_by":"profiles"},
  returns: {"branch_id":"branches","created_by":"profiles","customer_id":"customers","invoice_id":"invoices","organization_id":"organizations"},
  supplier_payments: {"branch_id":"branches","created_by":"profiles","organization_id":"organizations","purchase_id":"supplier_purchases","supplier_id":"suppliers"},
  customer_ledger_entries: {"branch_id":"branches","created_by":"profiles","credit_payment_id":"credit_payments","customer_id":"customers","invoice_id":"invoices","organization_id":"organizations","payment_id":"payments"},
  supplier_ledger_entries: {"branch_id":"branches","created_by":"profiles","organization_id":"organizations","payment_id":"supplier_payments","purchase_id":"supplier_purchases","supplier_id":"suppliers"},
  invoice_item_stock_allocations: {"invoice_id":"invoices","invoice_item_id":"invoice_items","organization_id":"organizations","product_id":"products","stock_lot_id":"product_stock_lots"},
  stock_movements: {"branch_id":"branches","created_by":"profiles","invoice_id":"invoices","invoice_item_id":"invoice_items","organization_id":"organizations","product_id":"products","stock_lot_id":"product_stock_lots"},
  supplier_purchase_items: {"organization_id":"organizations","product_id":"products","purchase_id":"supplier_purchases","stock_lot_id":"product_stock_lots"},
  return_items: {"invoice_id":"invoices","invoice_item_id":"invoice_items","organization_id":"organizations","product_id":"products","return_id":"returns"},
  return_stock_allocations: {"organization_id":"organizations","product_id":"products","return_id":"returns","return_item_id":"return_items","stock_lot_id":"product_stock_lots"},
  cash_shifts: {"branch_id":"branches","closed_by":"profiles","opened_by":"profiles","organization_id":"organizations"},
  expenses: {"archived_by":"profiles","branch_id":"branches","created_by":"profiles","organization_id":"organizations"},
  repairs: {"branch_id":"branches","created_by":"profiles","customer_id":"customers","organization_id":"organizations"},
  daily_closings: {"branch_id":"branches","finalized_by":"profiles","organization_id":"organizations"},
  staff_permissions: {"organization_id":"organizations","profile_id":"profiles"},
  loss_prevention_events: {"actor_id":"profiles","branch_id":"branches","invoice_id":"invoices","organization_id":"organizations","product_id":"products"},
  audit_logs: {"actor_id":"profiles","branch_id":"branches","organization_id":"organizations"},
};

export const SOURCE_BOOLEAN_FIELDS = new Set("is_archived allow_sell_at_loss_snapshot is_active requires_account_number requires_provider requires_reference allow_sell_at_loss restock can_sell can_discount can_return can_void_invoice can_view_reports can_manage_stock can_sell_at_loss can_change_settings".split(" "));
